# Generated by Django 5.2.7 on 2025-10-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringAnalysis',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField(unique=True)),
                ('properties', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
